// POST /api/verify-license
// Verifies a license key generated by the webhook handler.
// Body: { licenseKey: "MLS-..." }
//
// License keys are stored in a simple in-memory Map for sandbox testing.
// For production, replace with a database (e.g. Vercel KV, Supabase, etc.)
const { cors, PRICE_CREDITS } = require('./_helpers');

// ── In-memory license store (server-level, persists per-instance) ──
// Format: key → { credits, label, used: false, createdAt, txnId }
// NOTE: This resets on each cold start. For production use a real database.
if (!global._licenseStore) {
  global._licenseStore = new Map();
}
const licenseStore = global._licenseStore;

module.exports = async function handler(req, res) {
  cors(res);
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { licenseKey } = req.body || {};
  if (!licenseKey || typeof licenseKey !== 'string' || licenseKey.length < 8) {
    return res.status(400).json({ valid: false, error: 'Invalid key format' });
  }

  const entry = licenseStore.get(licenseKey);
  if (!entry) {
    return res.status(404).json({ valid: false, error: 'License key not found' });
  }

  if (entry.used) {
    return res.status(409).json({ valid: false, error: 'License key already redeemed' });
  }

  // Mark as used
  entry.used = true;
  entry.redeemedAt = new Date().toISOString();
  licenseStore.set(licenseKey, entry);

  return res.status(200).json({
    valid: true,
    credits: entry.credits,
    label: entry.label,
    txnId: entry.txnId,
  });
};

// Export store so webhook handler can write to it
module.exports._licenseStore = licenseStore;
